export const LOGIN_TEXTS = {
  BRAND_SUBTITLE: 'DASHBOARD DE CONTROL PARA BOX DE CROSSFIT',
  FEATURE_TITLE_1: 'Toda la información de tu box,',
  FEATURE_TITLE_2: 'en un solo lugar.',
  FEATURE_DESC: 'Gestiona alumnos, clases, pagos, reportes y mucho más de forma simple y eficiente.',
  COPYRIGHT: '© 2026 Fitium. Todos los derechos reservados.',
  FORM_TITLE: 'Iniciar sesión',
  FORM_SUBTITLE: 'Bienvenido de nuevo. Inicia sesión para continuar.',
  LABEL_EMAIL: 'Correo electrónico',
  PLACEHOLDER_EMAIL: 'ejemplo@fitium.com',
  LABEL_PASSWORD: 'Contraseña',
  PLACEHOLDER_PASSWORD: '••••••••••••••',
  LINK_FORGOT_PASSWORD: '¿Olvidaste tu contraseña?',
  BTN_SUBMIT: 'Iniciar sesión',
  DIVIDER_TEXT: 'o continúa con',
  BTN_GOOGLE: 'Continuar con Google',
  FOOTER_TEXT: '¿No tienes cuenta?',
  FOOTER_LINK: 'Contacta a tu administrador',
};

export const DASHBOARD_TEXTS = {
  HOME: {
    TITLE: 'Dashboard',
    SUBTITLE: 'Resumen general del box',
  },
  KPIS: {
    INCOME: 'Ingresos mensuales',
    EXPENSES: 'Gastos mensuales',
    PROFIT: 'Ganancia neta',
    ACTIVE_STUDENTS: 'Alumnos activos',
    EXPIRED_MEMBERSHIPS: 'Mensualidades vencidas',
  },
  WIDGETS: {
    TODAYS_CLASSES: 'Clases del día',
    RESERVATIONS: 'Reservas',
    LOW_STOCK: 'Stock bajo',
    IMPORTANT_ALERTS: 'Alertas importantes',
    TOP_STUDENTS: 'Top alumnos',
    QUICK_ACTIONS: 'Acciones rápidas',
  }
};

export const COMMON_TEXTS = {
  SEARCH_PLACEHOLDER: 'Buscar por nombre o email...',
  BUTTON_EXPORT: 'Exportar',
  BUTTON_CANCEL: 'Cancelar',
  BUTTON_SAVE: 'Guardar cambios',
  BUTTON_CREATE: 'Crear',
  BUTTON_FILTERS: 'Filtros',
  STATUS_ACTIVE: 'Activo',
  STATUS_INACTIVE: 'Inactivo',
  TABLE_NO_RESULTS: 'No se encontraron resultados.',
  PAGINATION_SHOWING: 'Mostrando',
  PAGINATION_TO: 'a',
  PAGINATION_OF: 'de',
  PAGINATION_PREV: 'Anterior',
  PAGINATION_NEXT: 'Siguiente',
  PAGINATION_PAGE: 'Pág',
};

export const COACHES_TEXTS = {
  TITLE: 'Coaches',
  SUBTITLE: 'Gestiona los entrenadores de tu box.',
  SEARCH_COACH: 'Buscar coach...',
  BUTTON_ADD: 'Agregar coach',
  TABLE_COL_COACH: 'Coach',
  TABLE_COL_EMAIL: 'Email',
  TABLE_COL_STATUS: 'Estado',
  TABLE_COL_CREATED_AT: 'Fecha de creación',
  TABLE_COL_ACTIONS: 'Acciones',
  TABLE_NO_COACHES: 'No se encontraron coaches.',
  SIDEBAR_TITLE_CREATE: 'Crear coach',
  SIDEBAR_TITLE_EDIT: 'Editar coach',
  SIDEBAR_SUBTITLE_CREATE: 'Completa los datos para agregar un nuevo entrenador.',
  SIDEBAR_SUBTITLE_EDIT: 'Actualiza los datos del entrenador.',
  SECTION_PERSONAL: 'Información personal',
  SECTION_CREDENTIALS: 'Credenciales de acceso',
  SECTION_STATUS: 'Estado',
  LABEL_FIRST_NAME: 'Nombre',
  LABEL_LAST_NAME: 'Apellido',
  LABEL_EMAIL: 'Email',
  LABEL_PASSWORD: 'Contraseña (opcional)',
  PLACEHOLDER_PASSWORD: 'Mínimo 8 caracteres',
  HELP_PASSWORD: 'Si no defines una contraseña, el sistema generará una automáticamente.',
  LABEL_STATUS: 'Estado del coach',
  HELP_STATUS: 'Los coaches inactivos no podrán acceder al sistema.',
  PLACEHOLDER_FIRST_NAME: 'Ej: Marcos',
  PLACEHOLDER_LAST_NAME: 'Ej: Ruiz',
  PLACEHOLDER_EMAIL_INPUT: 'Ej: marcos.ruiz@fitium.com',
  BUTTON_CREATING: 'Creando...',
  BUTTON_SAVING: 'Guardando...',
  BUTTON_CREATE_COACH: 'Crear coach',
};

export const STUDENTS_TEXTS = {
  TITLE: 'Estudiantes',
  SUBTITLE: 'Gestiona todos los miembros de tu box.',
  SEARCH_STUDENT: 'Buscar estudiante...',
  SEARCH_STUDENT_OR_EMAIL: 'Buscar por nombre o email...',
  BUTTON_ADD: 'Agregar estudiante',
  TABLE_COL_STUDENT: 'Estudiante',
  TABLE_COL_CONTACT: 'Contacto',
  TABLE_COL_STATUS: 'Estado',
  TABLE_COL_NEXT_PAYMENT: 'Próximo pago',
  TABLE_COL_ACTIONS: 'Acciones',
  TABLE_NO_STUDENTS: 'No se encontraron estudiantes.',
  SIDEBAR_TITLE_CREATE: 'Crear estudiante',
  SIDEBAR_TITLE_EDIT: 'Editar estudiante',
  SIDEBAR_SUBTITLE_CREATE: 'Completa los datos básicos del nuevo alumno.',
  SIDEBAR_SUBTITLE_EDIT: 'Actualiza los datos del alumno.',
  SECTION_PHOTO: 'Foto de perfil',
  BTN_UPLOAD_PHOTO: 'Subir foto',
  HELP_PHOTO_1: 'JPG, PNG o WEBP',
  HELP_PHOTO_2: 'Máx. 2MB',
  SECTION_PERSONAL: 'Información personal',
  SECTION_CONTACT: 'Contacto',
  SECTION_ADDITIONAL: 'Información adicional',
  LABEL_FIRST_NAME: 'Nombre',
  LABEL_LAST_NAME: 'Apellido',
  LABEL_DNI: 'DNI / Documento',
  LABEL_BIRTHDATE: 'Fecha de nacimiento',
  LABEL_EMAIL: 'Correo electrónico',
  LABEL_PHONE: 'Teléfono',
  LABEL_EMERGENCY_PHONE: 'Teléfono de emergencia',
  LABEL_ADDRESS: 'Dirección',
  LABEL_ENROLLMENT_DATE: 'Fecha de inscripción',
  LABEL_STATUS: 'Estado',
  LABEL_NOTES: 'Notas',
  PLACEHOLDER_FIRST_NAME: 'Ej: Juan',
  PLACEHOLDER_LAST_NAME: 'Ej: Pérez',
  PLACEHOLDER_DNI: 'Ej: 40123456',
  PLACEHOLDER_EMAIL_INPUT: 'Ej: juan@email.com',
  PLACEHOLDER_PHONE: 'Ej: +54 11 1234 5678',
  PLACEHOLDER_EMERGENCY_PHONE: 'Ej: +54 11 8765 4321',
  PLACEHOLDER_ADDRESS: 'Ej: Av. Siempre Viva 742',
  PLACEHOLDER_NOTES: 'Agrega observaciones médicas, lesiones o información relevante...',
  BUTTON_CREATING: 'Creando...',
  BUTTON_SAVING: 'Guardando...',
  BUTTON_CREATE_STUDENT: 'Crear estudiante',
  BADGE_SIN_EMAIL: 'Sin email',
  BADGE_SIN_TELEFONO: 'Sin teléfono',
  LABEL_DESDE: 'Desde',
  BADGE_SIN_PAGO: 'Sin pago',
  BADGE_VENCIDA: 'Vencida',
  BADGE_EN_TERMINO: 'En término',
  KPI_ACTIVE_STUDENTS: 'Estudiantes activos',
  KPI_NEW_THIS_MONTH: 'Nuevos este mes',
  KPI_EXPIRING_WEEK: 'Por vencer esta semana',
  KPI_INACTIVE: 'Inactivos',
  KPI_VS_LAST_MONTH: 'vs mes anterior',
  KPI_VER_LISTA: 'Ver lista'
};

export const ROUTINES_TEXTS = {
  TITLE: 'Rutinas',
  SUBTITLE: 'Gestiona las rutinas de entrenamiento asignadas a tus estudiantes.',
  SEARCH_PLACEHOLDER: 'Buscar rutina o estudiante...',
  NEW_ROUTINE: 'Nueva rutina',
  TABLE_ROUTINE: 'Rutina',
  TABLE_STUDENT: 'Estudiante',
  TABLE_DAYS: 'Días',
  TABLE_PERIOD: 'Período',
  TABLE_COACH: 'Entrenador',
  TABLE_STATUS: 'Estado',
  TABLE_ACTIONS: 'Acciones',
};
